### ISSUE TITLE
Hit area seems small on alerts

### ISSUE THREAD

**Issue by kyliefk** [willowtreeapps/vocable-android#101]
The hit area on alerts seems small, making it difficult to dwell on.
<img width="769" alt="Screen Shot 2020-03-27 at 11 03 20 AM" src="https://user-images.githubusercontent.com/16560422/77769707-92a57900-701a-11ea-91a4-109f61546ba2.png">

**Comment by jennydoesthings** [comment]
Confirm fixed as of 1.4
