### ISSUE TITLE
Pointer disappears when trying to navigate to the lower portion of the screen in portrait mode.

### ISSUE THREAD

**Issue by Uma-mv** [willowtreeapps/vocable-android#107]
1. using a handset device in portrait, attempt to navigate to the arrows at the bottom of the screen.
2. The pointer disappears from the screen as the user moves their head towards the bottom of the screen.
Expected: pointer should be able to reach the pagination tiles
Actual: cursor is only capable of reaching the second column of the last row.

**Comment by rc-young** [comment]
Screen recording: 
[screen-20200406-115236_2.mp4.zip](https://github.com/willowtreeapps/vocable-android/files/4439469/screen-20200406-115236_2.mp4.zip)
