### ISSUE TITLE
When adding a saying, if the user rotates the device any characters that were previously entered are lost.

### ISSUE THREAD

**Issue by Uma-mv** [willowtreeapps/vocable-android#148]
**When adding a new category, if the user rotates device any characters that were previously entered are lost.**

**Steps to Reproduce:**
1. In the My Sayings screen, tap on the + sign to add a new saying
2. enter one or more characters for the saying name
3. rotate the device from landscape to portrait or vice versa. 
4. all the entered characters are no longer available

**Expected Behavior:**
Device rotation should still retain the entered characters or phrase(s).

**Comment by jennydoesthings** [comment]
Confirm fixed as of 1.4
