### ISSUE TITLE
Show Category Button Does Not Activate with Head Tracking

### ISSUE THREAD

**Issue by Uma-mv** [willowtreeapps/vocable-android#151]
Increase the size of Show Category so that the selection area is larger especially for better head tracking

**Comment by jennydoesthings** [comment]
**Steps to Reproduce:**

1. Open the app on a physical device with head tracking enabled.
2. Navigate to settings and then categories.
3. Click on the Hide icon for a category with head tracking.

**Expected Result:**
The category is hidden.

**Actual Result:**
The button is tapped on, but it doesn't actually activate the action.
