### ISSUE TITLE
Remove Preset Category Message

### ISSUE THREAD

**Issue by Uma-mv** [willowtreeapps/vocable-android#152]
Steps to Reproduce: 
- With headtracking enabled, navigate to Categories and select one of the preset categories
- There is an invisible "Remove Category" button just below the "Show Category" section
- Hover the pointer over this area (see screenshot)
- An "Are you sure?" message pops up

![vocable](https://user-images.githubusercontent.com/32228545/80004727-b086c200-8490-11ea-8753-d589f8b0057a.png)

**Comment by jennydoesthings** [comment]
Confirm fixed as of 1.4
