### ISSUE TITLE
Add an empty state for custom category

### ISSUE THREAD

**Issue by Uma-mv** [willowtreeapps/vocable-android#153]
**As a vocable app user, I would like to see an empty state message when I have just added a category**

**Acceptance Criteria**
- user navigates to the categories section of the app
- Add a new category by tapping on the + option
- After successfully adding a category, navigating to the category on the home screen displays empty state screen.
- After successfully adding a category, navigating to the detail view of that category in Settings would display an empty state screen.

**Designs on Home Screen:**
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=19%3A0

Design in Settings:
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=19%3A1

**Comment by jollygreenegiant** [comment]
Finished with #280 and #282
