### ISSUE TITLE
Textview does not scroll when entering a long custom phrase

### ISSUE THREAD

**Issue by nerdsosky** [willowtreeapps/vocable-android#158]
Steps to reproduce:
1. Launch application
2. Tap on keyboard button to bring up custom phrase screen
3. Start typing until the letters go past the edge of the screen

Expected Behavior:
The textview should scroll as the user types so that that they can see the current input being added

![Screenshot_20200422-164600_Vocable](https://user-images.githubusercontent.com/10504463/80115160-6534e800-8552-11ea-8ea8-1c742061d27a.jpg)

**Comment by jennydoesthings** [comment]
Confirm fixed as of 1.4
