### ISSUE TITLE
Automation: Tests for Presets 

### ISSUE THREAD

**Issue by Uma-mv** [willowtreeapps/vocable-android#168]
Presets 
- [ ] Click on the preset phrase and confirm it hits the selected state. 
- [ ] Select a different category, check that phrases change and new category is selected
- [ ] Scroll category list
- [ ] Scroll category list and check that chosen category remains chosen when carousel repeats
- [ ] Paging buttons go through pages of phrases
- [ ] Head tracking error “head tracking is paused. Move your head to resume”

https://docs.google.com/document/d/1WJXc1u2dv9UAWb4ZnYqPW1V-Bij48pIMas6is_2mgQo/edit

**Comment by jennydoesthings** [comment]
This automation is mostly in place except for head tracking.
