### ISSUE TITLE
Add Phrases to custom category

### ISSUE THREAD

**Issue by Uma-mv** [willowtreeapps/vocable-android#181]
**As a user, I would like the ability to create new phrases inside of my custom category so that I may use them from the main screen of Vocable**

**Acceptance criteria:**

- To access custom phrases, a user will navigate to the "Categories and Phrases" screen in Settings. Custom categories will have an additional detail screen (accessed by the right arrow) where they will have an option to add new phrases.
- Custom phrases are unique entities and identical phrases can exist in multiple categories. Deleting or editing an identical phrase from one category does not remove it or edit it in another category.
- Clicking the "add" button will begin the add/edit keyboard flow. If users exit the keyboard without saving, a discard progress alert will be triggered.
- User can add phrases to the custom category from the custom category flow, or from the keyboard "add" button.

**Test Note:**
Custom Phrases will be in English only for this ticket.

**Design:**
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=19%3A1

**Comment by jollygreenegiant** [comment]
Finished with #277
