### ISSUE TITLE
Delete phrase from custom category

### ISSUE THREAD

**Issue by Uma-mv** [willowtreeapps/vocable-android#183]
**As a user, I need the ability to delete a custom phrase from a custom category so that I can manage what's available.**

**AC:**
1. User can delete all custom phrases from a custom category but only individually (unless we have an easy bulk solution)
2. Users should be presented with a confirmation modal before deletion is completed. 
3. Deleted phrases cannot be recovered for now

Design:
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=19%3A1

**Comment by SashankPatel** [comment]
PR284 has been merged.  Closing out the ticket.
