### ISSUE TITLE
Tracking cursors persists on settings screen after disabling head tracking

### ISSUE THREAD

**Issue by nerdsosky** [willowtreeapps/vocable-android#194]
The orange cursor can still be seen on the settings screen after disabling head tracking selection

Steps:
Launch application
Open the settings
Disable head tracking
Navigate back to settings

Result: Orange tracking cursor is still displayed in the top left of the screen

Expected: You should not see the cursor if head tracking is disabled

![trackerPersists](https://user-images.githubusercontent.com/10504463/80535610-154d8b00-896f-11ea-9f1a-12de2568b1ae.png)

**Comment by kennethWTA** [comment]
Not sure if you want a separate issue, but there's a ~1 second delay to when entering the Settings screen as well as when exiting it.
App ver.: 1.3.1
Device: Pixel 3, Android 10.
