### ISSUE TITLE
Change "My Sayings" to "Favorites"

### ISSUE THREAD

**Issue by rc-young** [willowtreeapps/vocable-android#217]
The "My Sayings" category will be renamed to Favorites. Existing functionality will be retained.

AC:

- Category cannot be hidden

**Comment by jollygreenegiant** [comment]
My Sayings was hidden as part of the Custom Categories feature.  If a user had phrases in My Sayings before upgrading to 1.4, they were transferred to a custom category called My Sayings, and the My Sayings preset category was removed.
