### ISSUE TITLE
Editing a long custom phrase doesn't display on screen

### ISSUE THREAD

**Issue by stechkev** [willowtreeapps/vocable-android#224]
**Describe the bug**
When editing a custom phrase that is long enough to be wider than the screen length, the end of the custom phrase does not appear on screen

**To Reproduce**

1. navigate to edit my sayings
2. add a new custom phrase that is longer than the width of the screen size

**Expected behavior**

- the end of the phrase along with a cursor is visible so that adding on to the end or deleting characters is visible to the user

**Actual Behavior**

- the end of the phrase along with the cursor is completely off screen. This makes adding on to the end or deleting characters invisible to the user

fixed in this issue on the main keyboard screen: https://github.com/willowtreeapps/vocable-android/issues/158

**Comment by SashankPatel** [comment]
This issue is reproducible and still valid as of v1.3.3.  Reproduced on Pixel 2 API 30 emulator.
