### ISSUE TITLE
Vocable banner appears when navigating to settings page

### ISSUE THREAD

**Issue by stechkev** [willowtreeapps/vocable-android#225]
**Describe the bug**
When navigating into the app from background, if the app is resuming on the settings page, a banner will appear on screen, blocking the back button

**To Reproduce**

1. navigate to settings
2. background the app
3. resume app from background

**Expected behavior**

- no banner is displayed

**Actual Behavior**

- a banner is displayed, blocking the back button

**Screenshots**
![image](https://user-images.githubusercontent.com/43387938/81821778-45189900-9500-11ea-864d-e0ef9eb1cb82.png)

**Comment by rc-young** [comment]
@stechkev Could you verify if you're still seeing this behavior in 1.3.2?

**Comment by SashankPatel** [comment]
Checked on a simulator - Pixel 3a XL API 30 - Vocable version: v1.3.3 and logged behavior was  not occurring.  Tried with various other languages as well.

**Comment by SashankPatel** [comment]
Closing out as it is not reproducible.
