### ISSUE TITLE
Category settings do not persist on app upgrade

### ISSUE THREAD

**Issue by nerdsosky** [willowtreeapps/vocable-android#230]
**Describe the bug**
When the user upgrades the application their hidden categories and category order will be reset

**To Reproduce**
Launch application
Navigate to Settings -> Categories
Hide a category
Change the order of a category
Update the application
Navigate to Settings -> Categories

**Expected behavior**
Hidden categories are still hidden and the order is the same

**Actual Behavior**
Category order and visibility gets reset to default state

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung S7
 - OS: Android 8

**Comment by jollygreenegiant** [comment]
This was fixed in 1.4 and verified by Sashank.
