### ISSUE TITLE
Update Alert Modal Background Color

### ISSUE THREAD

**Issue by hlargen5** [willowtreeapps/vocable-android#237]
When there is no content on-screen, alert modals backgrounds are the same color as the app background. This is now updated in the design file.

Acceptance criteria:

- All alert modal backgrounds should be changed to #504B93 at 85% opacity (currently they are #201C5B).
- Alert modal backgrounds are shown anytime changes are made to custom categories and phrases (creating a new category/phrase, editing a category/phrase, and removing category/phrase. This update should be reflected globally.

Link to Figma:

Keyboard Edits:
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=35%3A5

Custom Category/Phrases:
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=19%3A1

**Comment by SashankPatel** [comment]
This has been implemented in Vocable version 1.4.0.
![Screen Shot 2020-09-14 at 11 29 04 AM (2)](https://user-images.githubusercontent.com/50410188/93105931-a2bf1c80-f67d-11ea-8d2b-7125442279fc.png)
