### ISSUE TITLE
General Updates to Categories Screen

### ISSUE THREAD

**Issue by hlargen5** [willowtreeapps/vocable-android#240]
**Acceptance Criteria:**

- The title "Categories" should change to "Categories and Phrases" on the Settings main screen.
- ~~The hide category toggle should be brought to the Category main screen beside the up and down arrows. When a category is toggled off, it should be moved to the end of the list and the ">" button and up and down arrows should be inaccessible, at 50% opacity.~~
- ~~For default categories (non-custom categories), the ">" icon that accesses the detail screen should be inaccessible, at 50% opacity, as these cannot be edited.~~

**Design:**

https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=19%3A1

**Comment by SashankPatel** [comment]
String text has been updated.  Closing out the ticket.
