### ISSUE TITLE
Duplicate Danish preset saying under Personal category

### ISSUE THREAD

**Issue by nerdsosky** [willowtreeapps/vocable-android#249]
**Describe the bug**
"Jeg har brug for et bad" is repeated twice under the Personal preset section in Danish locale

**To Reproduce**

1. Change device language to Danish
2. Open Application
3. Navigate to Personal section

**Expected behavior**
There should only be one phrase for the danish translation

**Actual Behavior**
Duplicated translation

**Screenshots**
![Screenshot_1590593893](https://user-images.githubusercontent.com/10504463/83041625-aff0c680-a00e-11ea-84d4-7177de31b9f2.png)

**Smartphone (please complete the following information):**
 - Device: Nexus 10
 - OS: Android 10

**Comment by rc-young** [comment]
This is technically correct as there's no differentiating between shower and bath in Danish. I've asked Kenneth if we could use a different word.

**Comment by rc-young** [comment]
appoved new translation with "brusebad" for "shower"

**Comment by jennydoesthings** [comment]
Confirm fixed as of 1.4
