### ISSUE TITLE
Missing Danish translations for Show Category 

### ISSUE THREAD

**Issue by nerdsosky** [willowtreeapps/vocable-android#250]
**Describe the bug**
The Show Category string is not displayed on Danish locale

**To Reproduce**
Change locale to dansk
Open application
Open Settings
Open Category Order
Select a category

**Expected behavior**
Translated string for show category is displayed

**Actual Behavior**
No string is displayed

**Screenshots**
![Screenshot_20200527-115741](https://user-images.githubusercontent.com/10504463/83044086-b6347200-a011-11ea-8c29-f30b02149f0e.png)

**Smartphone (please complete the following information):**
 - Device: Nexus 10
 - OS: Android 10

**Comment by jennydoesthings** [comment]
Confirm fixed as of 1.4
