### ISSUE TITLE
Long words are not correctly hyphenated in Danish locale

### ISSUE THREAD

**Issue by nerdsosky** [willowtreeapps/vocable-android#251]
**Describe the bug**
Certain words are too long in Danish and wrap to a second line without being hyphenated

**To Reproduce**
Change device locale to Danish
Open application
Open Settings
Open Selection Mode (Markeringstilstand)

**Expected behavior**
Word wraps with a hyphen

**Actual Behavior**
word is broken onto 2 lines with no hyphen

**Screenshots**
![Screenshot_20200527-115721](https://user-images.githubusercontent.com/10504463/83044518-47a3e400-a012-11ea-8e0f-dcfbbe7ad01e.png)

**Smartphone (please complete the following information):**
 - Device: Pixel XL
 - OS: Android 10

**Comment by rc-young** [comment]
This has been resolved in Crowdin - code changes shouldn't be needed.
