### ISSUE TITLE
Minor typos in the german translation

### ISSUE THREAD

**Issue by tmrd993** [willowtreeapps/vocable-android#259]
**Describe the bug**
There are some minor typos in the german translation of the app

**To Reproduce**
Change device locale to Germany
Navigate to the presets/timing settings

**Expected behavior**
File in question:
https://github.com/willowtreeapps/vocable-android/blob/develop/app/src/main/res/values-de/strings.xml

Line 20 reads, ">Dieser link wir außerhalb..." should be -> "Dieser **L**ink wir**d**..."
Line 48 reads, "Gelöschte Redewendung können ..." should be -> "Gelöschte Redewendung**en** können..."

The timing and sensitivity option for one second reads "1 zweite", I think it should be 1 Sekunde unless I am mistaken and it's some technical term I don't know about. Also "Sekunden" should be capitalized.

Line 115 reads, "Das macht Sinn" should be -> "Das ergibt Sinn".
Line 151 reads, "Ich brauche**n** eine Jacke" should be -> "Ich brauche eine Jacke"

There is another german strings.xml with similar typos:
https://github.com/willowtreeapps/vocable-android/blob/develop/app/src/main/res/values-de-rDE/strings.xml

Line 16 = same as Line 20 above
Line 63 reads, "Kategorie zeigen" should be  -> "Kategorie anzeigen" which is what it's called in the other file above.
Line 99 = same as Line 115 above
Line 135 = same as Line 151 above

**Screenshots**
![Timing settings typo](https://user-images.githubusercontent.com/47194464/88107998-6359df80-cba8-11ea-89d1-8965e08d0fa6.jpg)
![Preset typo](https://user-images.githubusercontent.com/47194464/88108026-71a7fb80-cba8-11ea-9504-ee3eebfc286f.jpg)

**Smartphone (please complete the following information):**
 - Device: [SM-T830]
 - OS: [Android 10]

**Comment by rc-young** [comment]
Issue had been resolved in: https://github.com/willowtreeapps/vocable-android/pull/260
