### ISSUE TITLE
Delete a custom category

### ISSUE THREAD

**Issue by nicholas-cook** [willowtreeapps/vocable-android#276]
**Acceptance Criteria**:

To delete an entire category, a user should navigate to the custom category detail screen and tap the trash can icon in the top right-hand corner. The user will be given a prompt to confirm deletion. If they confirm, this will delete the entire category and all of its custom phrases in both the Categories setting screen and the home screen. This will delete only any phrases associated with _only_ that category. If a phrase is associated with a category other than the one being deleted, the phrase won't be deleted from the other category.

**Design**:

https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=19%3A1

**Comment by SashankPatel** [comment]
PR279 was merged, and scenario has been covered in manual test case.
