### ISSUE TITLE
Resource IDs need to be remade on startup

### ISSUE THREAD

**Issue by jollygreenegiant** [willowtreeapps/vocable-android#291]
**Describe the bug**
Resource IDs need to be regenerated on startup to avoid resource IDs pointing to the wrong things, which could cause phrases to show up as category names.

**To Reproduce**
This is a little bit difficult to do - I think it can be reproduced by adding a bunch of things to a category, deleting the category, closing the app, and reopening it.

**Comment by SashankPatel** [comment]
Fix has been implemented, verified and merged.  Closing out the ticket.
