### ISSUE TITLE
Add to Category Pagination scroll button layout

### ISSUE THREAD

**Issue by SashankPatel** [willowtreeapps/vocable-android#301]
**Describe the bug**
Per the design, the next/prev buttons on the Add to Category screen are closer together on a tablet
My guess is this is to not have the user have to head track as far. 

**To Reproduce**
1.) Launch the app
2.) Navigate to Settings > Categories
3.) Add a new category
4.) Navigate back to the home screen
5.) Tap on the Keyboard button
6.) Enter text and tap on the save button.

**Expected behavior**
Add to Category screen to appear and the bottom navigation to be displayed as follows:
<img width="671" alt="Screen Shot 2020-09-11 at 12 59 32 PM" src="https://user-images.githubusercontent.com/50410188/92954450-78791f00-f431-11ea-9aaa-0333b5b29307.png">

**Actual Behavior**
bottom navigation appears as follows:
![Screen Shot 2020-09-11 at 1 20 04 PM](https://user-images.githubusercontent.com/50410188/92954558-a199af80-f431-11ea-9982-cf82ef50bfed.png)

**Smartphone (please complete the following information):**
 - Device: Pixel C
 - OS: Android 10 API 30

**Comment by jollygreenegiant** [comment]
Verified fixed as of 1.4
