### ISSUE TITLE
[Spike] Should the minSDKVersion be bumped to 27 - ARCore for Head Tracking not supported below Android 8.1

### ISSUE THREAD

**Issue by rhsalas3** [willowtreeapps/vocable-android#352]
Users running Android 7 (API 24) devices cannot install the Google ARCore required for head tracking. The minSDKVersion is set to 24 for the Vocable project, but it looks like [ARCore requires Android 8.1 or newer](https://developers.google.com/ar/devices) (API 27). We may not want to limit the number of users that can use our app by adjusting the min supported SDK. However, I wanted to make sure it was documented where the line in the sand is for the head tracking feature.

The site we referenced for what Android version numbers represent which APIs: https://developer.android.com/studio/releases/platforms#12

**Comment by willdenne** [comment]
I talked with @jollygreenegiant about this a while ago, and it seems that the API 27 is only for emulators. There are a limited number of devices that support ARCore and are under API 24-27, but they do exist.
That being said, it is only a small fraction of users and if we can't test with them it might not be worth it.

**Comment by PaulKlauser** [comment]
If we do the work the separate out the ARCore dependency for #401, then lower API users will still be able to use the app, albeit without head tracking. We should keep the min at 24 for greater exposure at this time.
