### ISSUE TITLE
Convert Preset to Custom Categories.

### ISSUE THREAD

**Issue by SashankPatel** [willowtreeapps/vocable-android#360]
Parity with iOS - we decided the preset categories should be treated as custom categories and allow for deletion and editing.

- Note there is a dependency for the Reset functionality #57 

- The following categories can be renamed and deleted: General, Basic Needs, Personal Care, Conversation, Environment, 123, My Sayings, Recents(?) 

- if any of these categories are edited and the app is reset the categories shall return to their default state.

**Comment by willdenne** [comment]
merged, in develop
