### ISSUE TITLE
Add UI tests to pipeline

### ISSUE THREAD

**Issue by acosta434** [willowtreeapps/vocable-android#447]
**Acceptance Criteria**:

* Existing UI tests are running within pipeline.

Currently only unit tests are running in the pipeline. 

Note: This should be completed with Firebase Test Lab. [Pilot Time](https://github.com/willowtreeapps/PilotTime-Android) can serve as an example and starting point.

**Comment by PaulKlauser** [comment]
Reopening as the tests aren't actually running in the automated pipeline. They're enabled, so we're part way there, but we need to run them on Firebase Test Lab to close this out.
