### ISSUE TITLE
Model and store preset phrases

### ISSUE THREAD

**Issue by PaulKlauser** [willowtreeapps/vocable-android#463]
Currently saved and preset phrases are indistinguishable. This makes it impossible for us to be able to update preset phrases after the user installs the app, a necessity in case we need to update translations.

Let's specifically model and store preset Phrases. Model shape is dependent on the outcome of #465.

All retrieving of phrases should delegate to just the presets. Adding new phrases will not be supported until #466.

**Comment by mattttvaughn** [comment]
Closed with #492. We are now modeling presets by storing their resource entry name (e.g. `"category_123_0"` is the resource entry name for a string defined like so`<string name="category_123_0">0</string>`) 

This allows preset strings to be edited or translated in real-time via resource qualifiers
