### ISSUE TITLE
Add saved phrase

### ISSUE THREAD

**Issue by PaulKlauser** [willowtreeapps/vocable-android#466]
The separation of preset and saved Phrases necessitates us to re-model and store saved phrases. Keep in mind, there is some existing code for this already, but don't be afraid to re-implement.

As a user, I want to be able to add a new phrase to a category.

### Scenario 1 - Home screen
**Given**: I am viewing a category
**When**: I select "Add Phrase"
**And**: Save the new phrase
**Then**: I should see the new phrase within that category

### Scenario 2 - Settings
**Given**: I am viewing a category
**When**: I select "Add Phrase"
**And**: Save the new phrase
**Then**: I should see the new phrase within that category

**Comment by PaulKlauser** [comment]
This appears to be largely implemented, except there's one remaining issue: if you add a phrase on the home screen, you need to change categories to see it appear.

**Comment by josmith42** [comment]
This should be implemented now. The only remaining thing is to remove the `editCategories` property from `EditCategoriesViewModel`, as it is no longer needed.
