### ISSUE TITLE
[SPIKE] Determine source of truth for translations

### ISSUE THREAD

**Issue by PaulKlauser** [willowtreeapps/vocable-android#467]
We use Crowdin for translations, and currently a number of our string resources for other languages just feature English.

Going to Crowdin, we have multiple projects, Android, iOS, a common project. It's unclear what source of truth we should be using for pulling translations into the app. We need this before going live.

Outcome:
* We know and document which Crowdin project to pull from, and we are confident in its content quality. 
* We remove projects that are not relevant or accurate.

**Comment by kaffn8ed27** [comment]
> We know and document which Crowdin project to pull from, and we are confident in its content quality.
* Android should use the Android project to translate in-app strings. Some strings differ across platforms, hence the need for separate Android and iOS projects.
* Quality is, as far as I can tell, going to be up to whomever translates the strings for us (this being a crowdsourced translation service)
> We remove projects that are not relevant or accurate.
* All of the existing projects are relevant

**Comment by kaffn8ed27** [comment]
@PaulKlauser in what forum should I document the above for posterity?
